name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.3.0
        with:
          # GitHub user name to read the contribution graph from (**required**)
          github_user_name: ${{ github.repository_owner }}
      
          # List of files to generate
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/github-snake-dark-2.gif?palette=github-dark&color_background=black&color_dots=#56306F,#6A3D8D,#7D4AAC,#9157CA,#A464E8

      - name: Commit and push the generated snake
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-snake.svg dist/github-snake-dark.svg dist/ocean.gif dist/github-snake-dark-2.gif
          git commit -m "Generated snake animation"
          git push
